-- Display all customers who live in 'Delhi'.
select
*
from customers
where lower(city) = 'mumbai';

-- Find the average rating of all restaurants in 'Mumbai'
select
city,
round(avg(rating),2) as avg_rating
from restaurants
where lower(city) = 'mumbai'
group by city;

-- list all customers who have placed at least one order. 

select
*
from customers as c
where exists(
	select 
	1
	from orders as o
	where c.customer_id = o.customer_id);

-- Display the total number of orders placed by each customer

select
customer_name,
count(order_id) as total_count_orders
from customers as c
join orders as o
on c.customer_id = o.customer_id
group by customer_name; 


-- Find the total revenue generated by each restaurant 

select
r.name,
sum(total_amount) as total_revenue
from restaurants as r
left join orders as o
on r.restaurant_id = o.restaurant_id
group by r.name
;

-- Find the top 5 restaurants with the highest average rating
select
restaurant_id,
name,
city
from restaurants
order by rating desc
limit 5;

-- Display all customers who have never placed an order

select
c.customer_id,
c.name,
c.city
from customers as c
left join orders as o
on c.customer_id = o.customer_id
where o.order_id is null; 

--  Find the number of orders placed by each customer in Mumbai 

select
c.customer_id,c.name,
count(o.order_id) as count_of_orders
from customers as c
join orders as o
on c.customer_id = o.customer_id
where lower(city) = 'mumbai'
group by c.customer_id,c.name;


-- Display all orders placed in the last 30 days

select
order_id,
customer_id,
order_date,
total_amount
from orders
where order_date >= now() - interval 30 day;

-- List all delivery partners who have completed more than 1 delivery

select
dp.name,
dp.partner_id,
count(od.order_id) as count_of_orders
from orderdelivery as od
join deliverypartners as dp
on od.partner_id = dp.partner_id
join deliveryupdates as du
on od.order_id = du.order_id
where du.status <>'Failed'
group by dp.partner_id,dp.name
having count(od.order_id) > 1;

-- Find the customers who have placed orders on exactly three different days.

select
c.name
from customers as c
join orders as o
on c.customer_id = o.customer_id
group by c.name
having count(distinct order_date) = 3; 


-- Find the delivery partner who has worked with the most different customers.

select
dp.partner_id,
dp.name,
count(distinct o.customer_id) as different_customer
from deliverypartners as dp
join orderdelivery as od
on dp.partner_id = od.partner_id
join orders as o
on o.order_id = od.order_id
group by dp.partner_id,
dp.name
order by different_customer desc
limit 1; 



